### ISSUE TITLE
bbr->identical_rtt_count >= 2 will only have two consecutive acks, not three

### ISSUE THREAD

**Issue by kuninchengdu** [imtiaztee/BBR-Advanced--BBR-A--Linux-Kernel-Code#1]
1. as title   
if (bbr->identical_rtt_count >= 2 || rs->rtt_us > 2*bbr->min_rtt_us)
   {
	return true;
   }
2.  rs->rtt_us may be -1，so you should check，or you will exec as follow：
bbr->saved_last_rtt = rs->rtt_us;

**Comment by imtiaztee** [comment]
1. identical_rtt_count is 1 only when current rtt is in similar range with previous rtt, it becomes two when the next rtt also falls in the same range, the rtt value is updated upon reception of ack, thus, prev_ack+curr_ack+next_ack = total 3 ack, therefore, we say for three consecutive ACK, not two

2. thanks, updated
