### ISSUE TITLE
“cwnd = min(cwnd/2, target_cwnd)” may termination tcp flow

### ISSUE THREAD

**Issue by kuninchengdu** [imtiaztee/BBR-Advanced--BBR-A--Linux-Kernel-Code#2]
as following code:
1. if (bbr_probe_congestion (sk, rs) && state == TCP_CA_Recovery && prev_state != TCP_CA_Recovery) {
then 
”bbr->next_rtt_delivered = tp->delivered“ will be executed
now bbr->packet_conservation is 1.

2. 	if (bbr->packet_conservation) {
then 
cwnd = min(cwnd/2, target_cwnd);

it's high probaliity to set cwnd smaller than inflight，then any new packet can not be sent。
so bbr->packet_conservation will not can be set to 0， then following ack can not trigger new send。

static bool bbr_set_cwnd_to_recover_or_restore(struct sock *sk, const struct rate_sample *rs, u32 acked, u32 *new_cwnd, u32 bw) {
	struct tcp_sock *tp = tcp_sk(sk);
	struct bbr *bbr = inet_csk_ca(sk);
	u8 prev_state = bbr->prev_ca_state;
	u8 state = inet_csk(sk)->icsk_ca_state;
	u32 cwnd = tp->snd_cwnd;
	if (rs->losses > 0)
		cwnd = max_t(s32, cwnd - rs->losses, 1);
	if (bbr_probe_congestion (sk, rs) && state == TCP_CA_Recovery && prev_state != TCP_CA_Recovery) {
		bbr->packet_conservation = 1;
		bbr->next_rtt_delivered = tp->delivered;
	} else if (prev_state >= TCP_CA_Recovery && state < TCP_CA_Recovery) {
		cwnd = max(cwnd, bbr->prior_cwnd);
		bbr->packet_conservation = 0;
	}
	bbr->prev_ca_state = state;
	if (bbr->packet_conservation) {
            u32 target_cwnd = bbr_target_cwnd(sk, bw, BBR_UNIT);
	    cwnd = min(cwnd/2, target_cwnd);
	    *new_cwnd = max(cwnd, bbr_cwnd_min_target);
	    bbr_set_pacing_rate(sk, bw, BBR_UNIT * 3 / 4);
            bbr_set_tso_segs_goal(sk);
	    return true;
	}
	*new_cwnd = cwnd;
	return false;
}

**Comment by imtiaztee** [comment]
i could not understand fully, however, the code you are saying about is the default BBR v1 (https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/tree/net/ipv4/tcp_bbr.c)

it doesnot concern our code

**Comment by kuninchengdu** [comment]
why bbr will exec “bbr->next_rtt_delivered = tp->delivered”， which meaning next bbr cycle will arrive until the ack after “bbr->next_rtt_delivered = tp->delivered” come。But now cwnd  halved， witch not care inflight packet，so it‘s 
high probaliity that cwnd will smaller than inflight， then any packet can not be sent，then  “!before(rs->prior_delivered, bbr->next_rtt_delivered” will not be satisfy in function ‘bbr_update_bw’ ，then bbr will not arrive next cycle。

That‘s why default bbr wil exec “  cwnd = tcp_packets_in_flight(tp) + acked” in function ‘bbr_set_cwnd_to_recover_or_restore’ ，it will guarantee that cwnd is bigger than inflight。
